---
- name: Deploy on all servers
  hosts: all_servers
  roles:
    - misc
    - users
    - storage

- name: Configure database
  hosts: database
  roles:
    - database

- name: Configure webserver
  hosts: web
  roles:
    - websites
    - dns
    - email

  # Website summary 
  post_tasks:
    - name: Website deployment summary
      debug:
        msg:
          - "WordPress deployed successfully"
          - "Site URL : http://{{ wp_domain }}"
          - "Admin URL: http://{{ wp_domain }}/wp-admin"
          - "DB name  : {{ wp_db_name }}"
          - "Admin user: {{ wp_admin_user }}"
          - " "
          - "--------------****--------------"
          - " "
          - "MediaWiki deployed successfully"
          - "Site URL : http://{{ mediawiki_domain }}"
          - "DB name  : {{ mediawiki_db_name }}"
          - "Admin user: {{ mediawiki_admin_user }}"
          - " "
          - "--------------****--------------"
          - " "
    - name: Email summary
      debug:
        msg: >-
          {{
          [
            '--------------****--------------',
            'Postfix deployment summary',
            '--------------****--------------',
            'Domain         : ' + postfix_mydomain,
            'Hostname       : ' + postfix_myhostname,
            'Networks       : ' + postfix_mynetworks,
            'Log            : /var/log/maillog',
            'Configured mailboxes:'
          ]
          + nexcore_users | map(attribute='name') | map('regex_replace','^(.*)$','  \1@' + postfix_mydomain) | list
          + [
            'Test email sent to ops01@' + postfix_mydomain,
            '--------------****--------------'
          ]
          }}