---
- name: Configure PHP
  import_tasks: php-fpm.yml

- name: Install WordPress
  import_tasks: wordpress.yml

- name: Install MediaWiki
  import_tasks: mediawiki.yml

- name: Configure Nginx
  import_tasks: nginx.yml