
php_version: "8.2"
shell: "/bin/bash"
webserver_user: nginx
webserver_group: nginx

user_groups:
  - ops
  - dev
  - marketing

nexcore_users:

  - name: ops01
    groups:
      - ops
    sudo: true
    ssh_key: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQCzsOPfAxDfJ5o//COKidzYDP6oTmN1ZWFK6IG2zrb+vqb4lgFvQZ64Orsmke6mpAsO3EjqOrKJru00bGAZyWdFo028Lq7A9BPDuxUK16opOaOlPclOMr+6fU6vOgI1tGZNZZwM1EZGUBmFeimXmDHpf1peajePtqlGt26is2IUiCok6kcZlx27cRVs3fVTPNY+T0F6/PRGY4/ebP+V22eYmY3YUQ1IGhaB5ULk4Hy0l9m2sDMtsgJFIRni+wfhiVDUYFk13KgR68HbJrDiA2otCPnJoX9Ot+tik9CPE2B9oJX4onqvfV0NQvjVsRIWaMr8/1hMG8PIETkOlAF0AXgn0208jg4xfVTxTlnLpbkIUn57u9tENrwWexPeqB+q2+uEoVy1rblSWKHKsGUJrL6hxSXvKXPeP/8Ux0WjnSvn1HY3DxaPYL0mSBYFj75FVKC+8bugYDnZIbmirgRfX1FIYoljXsl9kWkGtWJT2LQk3wLKu5n/AhRhT1c5Q9m3SqpyxFvATJ+2nvDhs0N5NAVeLr42s7aCulWCHKE3DnQX8d1oCD7PYTT31Z796ArwKtkaHWKlxAWxlBGuPBXPLQvb2j+5GBTFzEA7Pax7Wzg5lNidM7LT0UfdKD454xxKrBr0f1vzqbCVfQaMStRRmm6/g6m3nKMP8ZfeycRS1V9NgQ== dev01 Ansible generated key


  - name: dev01
    groups:
      - dev
    sudo: false
    ssh_key: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQC7cL22BraWoUmW/nzCcxyRGkcu8pH6PBmqzlMW10cX5CeVHf8ryhBh2B8nUOr4Fa3g4z/R9FV08YePjbKr0EqQADZHBhkUaRTrDXPxT9Fg/AkPUxBTehQk3/vBtAHF5VZgqcq8MR/aA/KSSeRMHBJ7sZoAGfLQOSy5Nd56KBKNw0bkB5twxGyQpXw2jtcpcyoV4skYH2nZzTxEiY9zh3ECuJvZrLDot111p6fYaqc08qPcvxFT4KJpGTGmXj/v9JZxQz0YaN7zkj85QFLQ5L2y4Mm4cSn0I1Aw0YsvBfkuWZpnbPnah+mbz2QrT2lo1pJiBqcDvlGK4t7B4BMZJGgdGbaTMI2jv9xjFDKNqrWD1s1rl5eVJX0wprL4WsszxJoMap34GwX2+JCt4ZOHiExPaQjqjV2DW0eIESQ9Q8plOzvcMFuZvkouNldiD7E2GXI9YXLJF4sGplRx5Fo8Oq9eR3KydRYPdPM6XlKCmxENcFVBMaipFBu366kQ23YOkfmO7Lkk6OZIQhxwcJlXkTRFNQfeiBRhQMsTEBR4L7qtzeboghwGr8kPQfJ5aDUu4rr/61fOBN0aYYOIZKY4rFn1pWfdE7cxiP4YjGW+yeW/dMq5X8eMHan8qwaxgWBz/pZYrtQMKYC9zNK+kEtlp8l1J+EIVe3BYD778XhBk83fmQ== dev02 Ansible generated key


  - name: dev02
    groups:
      - dev
    sudo: false
    ssh_key: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQCCHAiLf8sPH+ElFMfpU8TnJGGOzatdTeTkK/1kKjZi22e8UtJBVZhxR9Ao3n1yVbbK4Iv2K5Eck0cvTFv+7FHXbBm87RBoUfOyZvavkHca15YM4L/wV62yi119by4xhPFHlCESRvgsSxYBNgTzDxJXll0vGqXvG9UlnxC8AgJS++BMmWGwmxYklX4P0hneaHHmnIvQ2AX30n9QeSAtC/8upxW0TQvPiYiCpBC1axl8LI8iauYmTycvQ7s+DvsOrPHF9uxBPbYFbp9zOIw66PDHr6/2603geMxpVHtR40ay08w1CIW5rc/ZTn5vP1aqHRV70cKbPYVxtHWaOJxkZbcOj6bUm+lUxYJrfhc4MCiatO5WWTi4lhSbod8Upk4epN7eFhijrsl1axcctSa7VaEbfR7zU4HF3/nTXb2FR4lKQ0b64+Arr4w1egBeizf8j4GPU+YDNlFXCuM+NCDYoHrAfR2nHtV3Ecjnd3J7ZXNbKDr5+tnWJLVI+pAmUEaLLVtxhjd7+UnII0ZDEtQO9mnkRR19BSe76HKbhK+qAOojdytTm4WaHzNCyGEEa8D1VqnK0dStlZFR6hbVn6GcQdizhH/c1tqYFgNRx2Fl9YIX7HJRi/27NclhJWhyu6t3803U5la1J6xYTqzMm7Qvmv5uH1tYl26fts1VOmYOF/SD3w== mkt01 Ansible generated key


  - name: mkt01
    groups:
      - marketing
    sudo: false
    ssh_key: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQCQwdG28XUYcrnJSL/RFw7bUljp9q0lZSCJM/06TdZmyIXtrS6i1o3ws47KDSVNQal2ldpEWl5pIMUW3Hns6V3xLoS7bOAKtNVedBDzG0WX1bt6ShWmO1f8BpBIhbIxBtpeHUr7pPZANhTnyC2UzOaZqTTZaYMZnCJqp6MFXd1WgGcXB5JFDqYdvFc9SDfmmRm1IHf97/FMNn3FwherEuA3d7RzOKTMG6RZXHI8xhFSjc12Sr+COjS4IU7Kc/S7lI4ej0FqtluPySFKZMZgIXZhhiu8lJT39vwVCMto/IN9VhSNvNxBtgsBfhXQU/WQjNha1QW8D+XmtcTwPFq7DbHMZI60TMrpkzE8jQRbcfy0zS6xz3D/D6MWM1uCHOygfWbI7HZPNCYtyWqIThei9JdmeKkrAVxEVV1b4Rx5qcE7nOO0NMjHK2qPwNLykFbsUV92ZNVGRfGDzEkSKaMuqkqI0A2mxYTEtBzJKcnAtcjFfkaGRguK4Kdn+I3ZlNIGQ2tnxmpLrLyQn3fCFAtG9OeCHAVluaYmUAayd8Ipo7oy+v5Fre3jWUwlLxcab2JuUdenQvOBrjSCkdkiLhoZ93tqQTCajaPi1Hdp3h28Mn8ugu3eWQetFvQ8weTRJXx+Gle0nh/B+USps9LHL3dM9qAVk5/FCNHIQgm4CwGkXHSvmw== ops01 Ansible generated key

# Wordpress
wp_site_title: "NexCore"
wp_domain: www.nexcore.local
wp_dir: /var/www/wordpress

wp_db_name: nexcore_wp
wp_db_user: nexcore_wp-user
wp_admin_user: admin
wp_admin_email: admin@nexcore.local
wp_locale: en_US

# MediaWiki
mediawiki_version: "1.45"
mediawiki_minor: "1.45.3"
mediawiki_domain: wiki.nexcore.local
mediawiki_name: "NexCore Wiki"
mediawiki_install_dir: /var/www/mediawiki
mediawiki_db_type: mysql
mediawiki_db_name: nexcore_wiki
mediawiki_db_user: nexcore_wikiuser
mediawiki_db_password: "{{ vault_mediawiki_db_password }}"

mediawiki_admin_user: WikiAdmin
mediawiki_admin_password: "{{ vault_mediawiki_admin_password }}"

mediawiki_extensions:
  - VisualEditor
  - Cite
  - ParserFunctions
  - SyntaxHighlight_GeSHi
  - CodeEditor