
php_version: "8.2"
webserver_user: nginx
webserver_group: nginx

# Wordpress
wp_site_title: "NexCore"
wp_domain: www.nexcore.local
wp_dir: /var/www/wordpress
wp_db_name: nexcore_wp
wp_db_user: nexcore_wp-user
wp_admin_user: WP-admin
wp_admin_email: wp-admin@nexcore.local
wp_locale: en_US

# MediaWiki
mediawiki_version: "1.45"
mediawiki_minor: "1.45.3"
mediawiki_domain: wiki.nexcore.local
mediawiki_name: "NexCore Wiki"
mediawiki_install_dir: /var/www/mediawiki
mediawiki_db_type: mysql
mediawiki_db_name: nexcore_wiki
mediawiki_db_user: nexcore_wikiuser
mediawiki_db_password: "{{ vault_mediawiki_db_password }}"
mediawiki_admin_user: WikiAdmin
mediawiki_admin_password: "{{ vault_mediawiki_admin_password }}"
