- name: Install BIND packages
  dnf:
    name:
      - bind
      - bind-utils
    state: present

- name: Create /var/named 
  file:
    path:  /var/named
    owner: named
    group: named
    mode:  "0770"
    state: directory

- name: Set SELinux context on  DNS zone dir
  sefcontext:
    target:  "/var/named(/.*)?"
    setype:  named_zone_t
    state:   present
  notify: Restore selinux context

- name: Deploy named.conf
  template:
    src:   named.conf.j2
    dest:  /etc/named.conf
    owner: named
    group: named
    mode:  "0640"
  notify: Restart named

- name: Deploy nexcore zone file
  template:
    src:   nexcore.local.zone.j2
    dest:  "{{ dns_zone_file }}"
    owner: named
    group: named
    mode:  "0640"
  notify: Restart named

- name: Enable and start named
  service:
    name:    named
    enabled: true
    state:   started




