- name: Restart NetworkManager
  ansible.builtin.service:
    name: NetworkManager
    state: restarted

- name: Reload NetworkManager 
  ansible.builtin.command:
    cmd: nmcli connection up "{{ nm_connection.stdout_lines[0] }}"
  changed_when: true

- name: Restart rsyslog
  ansible.builtin.service:
    name:  rsyslog
    state: restarted
