---
- name: restart php-fpm
  systemd:
    name: php-fpm         
    state: restarted

- name: reload nginx
  systemd:
    name: nginx
    state: reloaded

- name: restorecon wordpress
  command: restorecon -Rv {{ wp_dir }}
  changed_when: false

- name: restorecon wordpress
  command: restorecon -Rv {{ mediawiki_install_dir }}
  changed_when: false