---
- name: Deploy hosts file
  import_tasks: hosts.yml

- name: Configure packages
  import_tasks: packages.yml
  
- name: Configure firewall
  import_tasks: firewall.yml

- name: Setup resolvers
  import_tasks: resolvers.yml

- name: Setup logs
  import_tasks: logs.yml

- name: Setup healthcheck
  import_tasks: health-check.yml